name = "newlife-united"
compatibility_date = "2024-04-10"
pages_build_output_dir = "./"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "newlife-crm"
database_id = "82409576-39ef-4bf4-904d-bf5611d9f013"

# R2 Bucket Binding for Images
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "newlife-images"
jurisdiction = "eu"
