-- Newlife United · May–December 2026 calendar.
-- Replaces all existing events with the church's published "save the dates".
-- Recurring items (Growth Track, Baby Dedications) are stored once per month
-- they appear under, as requested. Run: npm run db:events  (see package.json)
DELETE FROM events;

INSERT INTO events (id, title, description, date, time, end_time, location, image_url, page, tag, featured, is_active, created_at, updated_at) VALUES
-- ── MAY 2026 ──────────────────────────────────────────────────────
('evt_202605_series',      'How To Walk In Faith',                          '',                                                                                  '2026-05-01', '',      '',      '', 'assets/worship.png',   'events', 'SERMON SERIES',    0, 1, datetime('now'), datetime('now')),
('evt_202605_growth',      'Growth Track',                                  'Runs every month.',                                                                 '2026-05-01', '',      '',      '', 'assets/signboard.png', 'events', 'GROWTH TRACK',     0, 1, datetime('now'), datetime('now')),
('evt_202605_dedication',  'Baby Dedications',                              'Every second month.',                                                               '2026-05-01', '',      '',      '', 'assets/lobby.png',     'events', 'BABY DEDICATIONS', 0, 1, datetime('now'), datetime('now')),
-- ── JUNE 2026 ─────────────────────────────────────────────────────
('evt_202606_series',      'The Power of Giving',                           '',                                                                                  '2026-06-01', '',      '',      '', 'assets/worship.png',   'events', 'SERMON SERIES',    0, 1, datetime('now'), datetime('now')),
('evt_202606_growth',      'Growth Track',                                  'Runs every month.',                                                                 '2026-06-01', '',      '',      '', 'assets/signboard.png', 'events', 'GROWTH TRACK',     0, 1, datetime('now'), datetime('now')),
('evt_202606_dreamteam',   'Dream Team Gathering',                          'No prayer meeting that week.',                                                      '2026-06-10', '',      '',      '', 'assets/pastor.png',    'events', 'DREAM TEAM',       0, 1, datetime('now'), datetime('now')),
-- ── JULY 2026 ─────────────────────────────────────────────────────
('evt_202607_series',      'Holy Spirit',                                   '',                                                                                  '2026-07-01', '',      '',      '', 'assets/worship.png',   'events', 'SERMON SERIES',    0, 1, datetime('now'), datetime('now')),
('evt_202607_growth',      'Growth Track',                                  'Runs every month.',                                                                 '2026-07-01', '',      '',      '', 'assets/signboard.png', 'events', 'GROWTH TRACK',     0, 1, datetime('now'), datetime('now')),
('evt_202607_dreamteam',   'Dream Team Gathering',                          'No prayer meeting that week.',                                                      '2026-07-22', '',      '',      '', 'assets/pastor.png',    'events', 'DREAM TEAM',       0, 1, datetime('now'), datetime('now')),
('evt_202607_dedication',  'Baby Dedications',                              'Every second month.',                                                               '2026-07-01', '',      '',      '', 'assets/lobby.png',     'events', 'BABY DEDICATIONS', 0, 1, datetime('now'), datetime('now')),
-- ── AUGUST 2026 ───────────────────────────────────────────────────
('evt_202608_series',      'Becoming Fruitful',                             '',                                                                                  '2026-08-01', '',      '',      '', 'assets/worship.png',   'events', 'SERMON SERIES',    0, 1, datetime('now'), datetime('now')),
('evt_202608_growth',      'Growth Track',                                  'Runs every month.',                                                                 '2026-08-01', '',      '',      '', 'assets/signboard.png', 'events', 'GROWTH TRACK',     0, 1, datetime('now'), datetime('now')),
-- ── SEPTEMBER 2026 ────────────────────────────────────────────────
('evt_202609_series',      'Becoming Fruitful',                             '',                                                                                  '2026-09-01', '',      '',      '', 'assets/worship.png',   'events', 'SERMON SERIES',    0, 1, datetime('now'), datetime('now')),
('evt_202609_arc',         'Arc Conference',                                '2–3 September. No Dream Team Gathering that month. No prayer meeting that week.',    '2026-09-02', '09:00', '15:00', '', 'assets/building.png',  'events', 'CONFERENCE',       0, 1, datetime('now'), datetime('now')),
('evt_202609_griefshare',  'Care Ministries – Grief Share',                 'Runs 7 September – 30 November.',                                                   '2026-09-07', '',      '',      '', 'assets/lobby.png',     'events', 'CARE MINISTRY',    0, 1, datetime('now'), datetime('now')),
('evt_202609_divorce',     'Care Ministries – Divorce & Single Parenting',  'Runs 7 September – 30 November.',                                                   '2026-09-07', '',      '',      '', 'assets/lobby.png',     'events', 'CARE MINISTRY',    0, 1, datetime('now'), datetime('now')),
('evt_202609_growth',      'Growth Track',                                  'Runs every month.',                                                                 '2026-09-01', '',      '',      '', 'assets/signboard.png', 'events', 'GROWTH TRACK',     0, 1, datetime('now'), datetime('now')),
('evt_202609_dreamteam',   'Dream Team Gathering',                          'No prayer meeting that week.',                                                      '2026-09-02', '',      '',      '', 'assets/pastor.png',    'events', 'DREAM TEAM',       0, 1, datetime('now'), datetime('now')),
('evt_202609_dedication',  'Baby Dedications',                              'Every second month.',                                                               '2026-09-01', '',      '',      '', 'assets/lobby.png',     'events', 'BABY DEDICATIONS', 0, 1, datetime('now'), datetime('now')),
-- ── OCTOBER 2026 ──────────────────────────────────────────────────
('evt_202610_series',      'Faith It Till You Make It',                     '',                                                                                  '2026-10-01', '',      '',      '', 'assets/worship.png',   'events', 'SERMON SERIES',    0, 1, datetime('now'), datetime('now')),
('evt_202610_growth',      'Growth Track',                                  'Runs every month.',                                                                 '2026-10-01', '',      '',      '', 'assets/signboard.png', 'events', 'GROWTH TRACK',     0, 1, datetime('now'), datetime('now')),
('evt_202610_dreamteam',   'Dream Team Gathering',                          'No prayer meeting that week.',                                                      '2026-10-14', '',      '',      '', 'assets/pastor.png',    'events', 'DREAM TEAM',       0, 1, datetime('now'), datetime('now')),
-- ── NOVEMBER 2026 ─────────────────────────────────────────────────
('evt_202611_series',      'Connecting With God Through Worship',           '',                                                                                  '2026-11-01', '',      '',      '', 'assets/worship.png',   'events', 'SERMON SERIES',    0, 1, datetime('now'), datetime('now')),
('evt_202611_growth',      'Growth Track',                                  'Runs every month.',                                                                 '2026-11-01', '',      '',      '', 'assets/signboard.png', 'events', 'GROWTH TRACK',     0, 1, datetime('now'), datetime('now')),
('evt_202611_dreamteam',   'Dream Team Gathering',                          'No prayer meeting that week.',                                                      '2026-11-25', '',      '',      '', 'assets/pastor.png',    'events', 'DREAM TEAM',       0, 1, datetime('now'), datetime('now')),
('evt_202611_dedication',  'Baby Dedications',                              'Every second month.',                                                               '2026-11-01', '',      '',      '', 'assets/lobby.png',     'events', 'BABY DEDICATIONS', 0, 1, datetime('now'), datetime('now')),
-- ── DECEMBER 2026 ─────────────────────────────────────────────────
('evt_202612_series',      'Christmas Series',                              '',                                                                                  '2026-12-01', '',      '',      '', 'assets/worship.png',   'events', 'SERMON SERIES',    0, 1, datetime('now'), datetime('now')),
('evt_202612_carols',      'Christmas Carols',                              '',                                                                                  '2026-12-11', '',      '',      '', 'assets/worship.png',   'events', 'SPECIAL',          0, 1, datetime('now'), datetime('now')),
('evt_202612_christmasday','Christmas Day Service',                         'Jesus, Light Of The World.',                                                        '2026-12-25', '',      '',      '', 'assets/building.png',  'events', 'SPECIAL',          0, 1, datetime('now'), datetime('now'));
